DROP TABLE "BIEE_BIPLATFORM"."RM_NQ_TEMP_HISTORY" ;
CREATE TABLE "BIEE_BIPLATFORM"."RM_NQ_TEMP_HISTORY"
  (
    "FMW_ENV"           VARCHAR2(64 BYTE),
    "SAMPLE_TIME_EPOCH" NUMBER,
    "SAMPLE_TIMESTAMP"  DATE,
    "FMW_COMPONENT"     VARCHAR2(64 BYTE),
    "BYTES_USED"        NUMBER,
    CONSTRAINT "PK1" PRIMARY KEY ("FMW_ENV", "FMW_COMPONENT", "SAMPLE_TIMESTAMP")
  ) ;

--select fmw_env,to_char(SAMPLE_TIMESTAMP,'YYYY-MM-DD HH24:MI:SS') as sample_timestamp,component,bytes_used from BIEE_BIPLATFORM.RM_NQ_TEMP_HISTORY;

CREATE OR REPLACE VIEW BIEE_BIPLATFORM.RM_NQ_TEMP_HISTORY_SUMMARY AS
  SELECT to_date(TO_CHAR(sample_timestamp,'YYYY-MM-DD HH24:MI'),'YYYY-MM-DD HH24:MI') AS SAMPLE_TIMESTAMP,
    FMW_ENV,
    FMW_COMPONENT,
    MAX(BYTES_USED)           AS MAX_BYTES_USED,
    MAX(BYTES_USED)/1024/1024 AS MAX_MB_USED
  FROM BIEE_BIPLATFORM.RM_NQ_TEMP_HISTORY
  GROUP BY to_date(TO_CHAR(sample_timestamp,'YYYY-MM-DD HH24:MI'),'YYYY-MM-DD HH24:MI') ,
    FMW_ENV,
    FMW_COMPONENT;

--select to_char(SAMPLE_TIMESTAMP,'YYYY-MM-DD HH24:MI:SS') as sample_timestamp
--,FMW_ENV
--,FMW_COMPONENT
--,MAX_BYTES_USED
--,MAX_MB_USED
--FROM RM_NQ_TEMP_HISTORY_SUMMARY h;
