LOAD DATA 
INFILE '/u01/data/obi-temp/obiee.biee.du.tsv.stage'
BADFILE '/u01/data/obi-temp/obiee.biee.du.bad'
DISCARDFILE '/u01/data/obi-temp/obiee.biee.du.discard'
APPEND
INTO TABLE RM_NQ_TEMP_HISTORY
FIELDS TERMINATED BY '\t'
OPTIONALLY ENCLOSED BY '"' AND '"'
(
  FMW_ENV CHAR(4000)
, SAMPLE_TIME_EPOCH CHAR(4000)
, SAMPLE_TIMESTAMP DATE 'YYYY-MM-DD"T"HH24:MI:SS'
, FMW_COMPONENT CHAR(4000)
, BYTES_USED CHAR(4000)  
) 
